export const SET_FORM = 'SET_FORM'
export const SET_ROLES = 'SET_ROLES'
export const SAVE_TOKENS = 'SAVE_TOKENS'
export const SAVE_USER = 'SAVE_USER'
export const SET_QUALIFICATION = 'SET_QUALIFICATION'